# Generated by Django 5.0.1 on 2024-01-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust_crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
