# Generated by Django 5.0.1 on 2024-01-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust_crm_app', '0002_rename_f_name_record_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
